### ISSUE TITLE
May I have the csv files(training and testing)

### ISSUE THREAD

**Issue by poult-lab** [seorim0/ResUNet-LC#1]
Hello, Author. Your work is awesome! Can we have the CSV files that you mentioned in the md file?

**Comment by poult-lab** [comment]
I have made own csv files, I will close this issue.

**Comment by seorim0** [comment]
Sorry for the late reply, and thank you for your  attention  with our study.

I will send you the CSV files that I used for the proposed paper.

After downloading the dataset through the link sent in the previous email,
create a folder according to the path shown in the CSV file and move the
downloaded dataset to that location.

If you have any further questions or require additional clarification,
please do not hesitate to contact me (email or github issues).

Sincerely,
Seorim

 test_dataset.csv
<https://drive.google.com/file/d/1CJDky3ZmRx-9ylFi08g0VifKX4I503W3/view?usp=drive_web>
 train_dataset.csv
<https://drive.google.com/file/d/1UWXFUlyXH0yPqpPZmNzG5pxRDjANpERx/view?usp=drive_web>


2024년 7월 2일 (화) 오후 5:46, Huawei Jiang ***@***.***>님이 작성:

**Comment by poult-lab** [comment]
Thank you for your reply. This is very helpful.
