### ISSUE TITLE
why is the lead combinator(LC) so effective

### ISSUE THREAD

**Issue by poult-lab** [seorim0/ResUNet-LC#3]
Hello author,

Thank you for your work; the result is very impressive. We can see that the lead combinator (LC) is very useful, increasing the AUPRC by almost 20%.

Could you explain why the LC is so effective and what inspired you to design it?

Looking forward to your reply.

**Comment by seorim0** [comment]
Hello! Thank you for showing interest in our research.

While studying ECG, we realized that analyzing both the inter-lead information and the information within each lead (intra-lead) is important.

And recently, several papers have proposed various structures to address this aspect effectively. One of these structures is a 2D framework, which is simple yet effective for our purposes.

However, we observed that even though these 2D models are designed to extract inter-lead and intra-lead information efficiently, they eventually compress this information using a simple pooling module without considering the lead-specific details during the final classification stage.

We thught that enhancing the final classification process to consider these lead-specific details could improve the model's performance. This led us to propose the Lead Combiner.

And we used the basic framework commonly employed in other papers to combine features for the detailed module structure.

**Comment by poult-lab** [comment]
Hello author, thank you for your reply. This response is very informative. 
In your last sentence, you mentioned that 'the lead combiner is a basic framework commonly employed in other papers.' 
Could you please provide references to those other papers? That would be very helpful.
